In [1]:
import pandas as pd
sources_path = '../0sources'
clean_data_path = '../2clean_data/'

In [2]:
df = pd.read_csv(f"{sources_path}/GSE147507.tsv", sep='\t')
meta = pd.read_csv(f"{clean_data_path}/colData.GSE147507.csv")

In [3]:
meta

,cell_type,group,subject_status,GSM
Series15_HealthyLungBiopsy_1,Lung Biopsy,Control,"No treatment - healthy 77 years old, male",GSM4462413
Series15_HealthyLungBiopsy_2,Lung Biopsy,Control,"No treatment - healthy 72 years old, male",GSM4462414
Series15_COVID19Lung_1,Lung Biopsy,COVID,No treatment; >60 years old male COVID-19 dece...,GSM4462415
Series15_COVID19Lung_2,Lung Biopsy,COVID,No treatment; >60 years old male COVID-19 dece...,GSM4462416

In [4]:
study_columns = list(meta.index)
study_columns

['Series15_HealthyLungBiopsy_1',
 'Series15_HealthyLungBiopsy_2',
 'Series15_COVID19Lung_1',
 'Series15_COVID19Lung_2']

In [5]:
study_samples = df.loc[:, study_columns]
study_samples

,Series15_HealthyLungBiopsy_1,Series15_HealthyLungBiopsy_2,Series15_COVID19Lung_1,Series15_COVID19Lung_2
DDX11L1,0,0,0,0
WASH7P,140,261,0,0
FAM138A,0,0,0,0
FAM138F,0,0,0,0
OR4F5,0,0,0,0
...,...,...,...,...
CDY1B,0,0,0,0
CDY1,0,0,0,0
CSPG4P1Y,0,0,0,0
GOLGA2P3Y,0,0,0,0
GOLGA2P2Y,0,0,0,0

In [6]:
study_samples.to_csv(f"{clean_data_path}/GSE147507.csv")