In [1]:
import pandas as pd

In [6]:
Data0 = pd.read_excel('../data_sources/Old/GSE147507/GSE147507.xlsx')

In [7]:
Data0.index = list(Data0['Unnamed: 0'])
Data0.drop(columns = ['Unnamed: 0']+[_ for _ in list(Data0.columns) if _[6] in ['3','4','8']],
          inplace = True)
Data0.drop(columns = list(Data0.loc[:,'Series9_NHBE_IAV_1':'Series9_NHBE_IAV_4'])+list(Data0.loc[:,'Series9_NHBE_IAVdNS1_1':'Series9_NHBE_IAVdNS1_4']), 
          inplace = True )

In [9]:
for column in Data0.columns: print(column)

Series1_NHBE_Mock_1
Series1_NHBE_Mock_2
Series1_NHBE_Mock_3
Series1_NHBE_SARS-CoV-2_1
Series1_NHBE_SARS-CoV-2_2
Series1_NHBE_SARS-CoV-2_3
Series2_A549_Mock_1
Series2_A549_Mock_2
Series2_A549_Mock_3
Series2_A549_SARS-CoV-2_1
Series2_A549_SARS-CoV-2_2
Series2_A549_SARS-CoV-2_3
Series5_A549_Mock_1
Series5_A549_Mock_2
Series5_A549_Mock_3
Series5_A549_SARS-CoV-2_1
Series5_A549_SARS-CoV-2_2
Series5_A549_SARS-CoV-2_3
Series6_A549-ACE2_Mock_1
Series6_A549-ACE2_Mock_2
Series6_A549-ACE2_Mock_3
Series6_A549-ACE2_SARS-CoV-2_1
Series6_A549-ACE2_SARS-CoV-2_2
Series6_A549-ACE2_SARS-CoV-2_3
Series7_Calu3_Mock_1
Series7_Calu3_Mock_2
Series7_Calu3_Mock_3
Series7_Calu3_SARS-CoV-2_1
Series7_Calu3_SARS-CoV-2_2
Series7_Calu3_SARS-CoV-2_3
Series9_NHBE_Mock_1
Series9_NHBE_Mock_2
Series9_NHBE_Mock_3
Series9_NHBE_Mock_4
Series9_NHBE_IFNB_4h_1
Series9_NHBE_IFNB_4h_2
Series9_NHBE_IFNB_6h_1
Series9_NHBE_IFNB_6h_2
Series9_NHBE_IFNB_12h_1
Series9_NHBE_IFNB_12h_2
Series15_HealthyLungBiopsy_2
Series15_HealthyLungBiopsy_1
Series15_COVID19Lung_2
Series15_COVID19Lung_1
Series16_A549-ACE2_Mock_1
Series16_A549-ACE2_Mock_2
Series16_A549-ACE2_Mock_3
Series16_A549-ACE2_SARS-CoV-2_1
Series16_A549-ACE2_SARS-CoV-2_2
Series16_A549-ACE2_SARS-CoV-2_3
Series16_A549-ACE2_SARS-CoV-2_Rux_1
Series16_A549-ACE2_SARS-CoV-2_Rux_2
Series16_A549-ACE2_SARS-CoV-2_Rux_3

In [13]:
Data = Data0.copy()

In [14]:
Data[list(Data.columns)[0]]/29

DDX11L1      0.0
WASH7P       1.0
FAM138A      0.0
FAM138F      0.0
OR4F5        0.0
            ...
CDY1B        0.0
CDY1         0.0
CSPG4P1Y     0.0
GOLGA2P3Y    0.0
GOLGA2P2Y    0.0
Name: Series1_NHBE_Mock_1, Length: 21797, dtype: float64

In [15]:
Data0.index = list(Data0['Unnamed: 0'])
Data0.drop(columns = ['Unnamed: 0']+[_ for _ in list(Data0.columns) if _[6] in ['3','4','8']],
          inplace = True)

KeyError: 'Unnamed: 0'

In [9]:
Data0.columns

Index(['Unnamed: 0', 'Series1_NHBE_Mock_1', 'Series1_NHBE_Mock_2',
       'Series1_NHBE_Mock_3', 'Series1_NHBE_SARS-CoV-2_1',
       'Series1_NHBE_SARS-CoV-2_2', 'Series1_NHBE_SARS-CoV-2_3',
       'Series2_A549_Mock_1', 'Series2_A549_Mock_2', 'Series2_A549_Mock_3',
       'Series2_A549_SARS-CoV-2_1', 'Series2_A549_SARS-CoV-2_2',
       'Series2_A549_SARS-CoV-2_3', 'Series3_A549_Mock_1',
       'Series3_A549_Mock_2', 'Series3_A549_RSV_1', 'Series3_A549_RSV_2',
       'Series4_A549_Mock_1', 'Series4_A549_Mock_2', 'Series4_A549_IAV_1',
       'Series4_A549_IAV_2', 'Series5_A549_Mock_1', 'Series5_A549_Mock_2',
       'Series5_A549_Mock_3', 'Series5_A549_SARS-CoV-2_1',
       'Series5_A549_SARS-CoV-2_2', 'Series5_A549_SARS-CoV-2_3',
       'Series6_A549-ACE2_Mock_1', 'Series6_A549-ACE2_Mock_2',
       'Series6_A549-ACE2_Mock_3', 'Series6_A549-ACE2_SARS-CoV-2_1',
       'Series6_A549-ACE2_SARS-CoV-2_2', 'Series6_A549-ACE2_SARS-CoV-2_3',
       'Series7_Calu3_Mock_1', 'Series7_Calu3_Mock_2', 'Series7_Calu3_Mock_3',
       'Series7_Calu3_SARS-CoV-2_1', 'Series7_Calu3_SARS-CoV-2_2',
       'Series7_Calu3_SARS-CoV-2_3', 'Series8_A549_Mock_1',
       'Series8_A549_Mock_2', 'Series8_A549_Mock_3', 'Series8_A549_RSV_1',
       'Series8_A549_RSV_2', 'Series8_A549_RSV_3', 'Series8_A549_HPIV3_3',
       'Series8_A549_HPIV3_2', 'Series8_A549_HPIV3_1', 'Series9_NHBE_Mock_1',
       'Series9_NHBE_Mock_2', 'Series9_NHBE_Mock_3', 'Series9_NHBE_Mock_4',
       'Series9_NHBE_IAV_1', 'Series9_NHBE_IAV_2', 'Series9_NHBE_IAV_3',
       'Series9_NHBE_IAV_4', 'Series9_NHBE_IAVdNS1_1',
       'Series9_NHBE_IAVdNS1_2', 'Series9_NHBE_IAVdNS1_3',
       'Series9_NHBE_IAVdNS1_4', 'Series9_NHBE_IFNB_4h_1',
       'Series9_NHBE_IFNB_4h_2', 'Series9_NHBE_IFNB_6h_1',
       'Series9_NHBE_IFNB_6h_2', 'Series9_NHBE_IFNB_12h_1',
       'Series9_NHBE_IFNB_12h_2', 'Series15_HealthyLungBiopsy_2',
       'Series15_HealthyLungBiopsy_1', 'Series15_COVID19Lung_2',
       'Series15_COVID19Lung_1', 'Series16_A549-ACE2_Mock_1',
       'Series16_A549-ACE2_Mock_2', 'Series16_A549-ACE2_Mock_3',
       'Series16_A549-ACE2_SARS-CoV-2_1', 'Series16_A549-ACE2_SARS-CoV-2_2',
       'Series16_A549-ACE2_SARS-CoV-2_3',
       'Series16_A549-ACE2_SARS-CoV-2_Rux_1',
       'Series16_A549-ACE2_SARS-CoV-2_Rux_2',
       'Series16_A549-ACE2_SARS-CoV-2_Rux_3'],
      dtype='object')

In [11]:
Data0.loc[:,'Series9_NHBE_IAV_1':'Series9_NHBE_IAV_4']

,Series9_NHBE_IAV_1,Series9_NHBE_IAV_2,Series9_NHBE_IAV_3,Series9_NHBE_IAV_4
0,0,0,0,0
1,102,26,21,7
2,0,0,0,0
3,0,0,0,0
4,0,0,0,0
...,...,...,...,...
21792,0,0,0,0
21793,0,0,0,0
21794,0,0,0,0
21795,0,0,0,0
21796,0,0,0,0

In [10]:
Series1 = Data.loc[:,list(S1 for S1 in list(Data.columns) if S1[6] == '1' and S1[7] == '_')].copy()

In [11]:
Series1

,Series1_NHBE_Mock_1,Series1_NHBE_Mock_2,Series1_NHBE_Mock_3,Series1_NHBE_SARS-CoV-2_1,Series1_NHBE_SARS-CoV-2_2,Series1_NHBE_SARS-CoV-2_3
DDX11L1,0,0,0,0,0,0
WASH7P,29,24,23,34,19,44
FAM138A,0,0,0,0,0,0
FAM138F,0,0,0,0,0,0
OR4F5,0,0,0,0,0,0
...,...,...,...,...,...,...
CDY1B,0,0,0,0,0,0
CDY1,0,0,0,0,0,0
CSPG4P1Y,0,0,0,0,0,0
GOLGA2P3Y,0,0,0,0,0,0
GOLGA2P2Y,0,0,0,0,0,0

In [15]:
Total_Gen = len(Data.index)
import statistics as sts

In [16]:
Series1['Promedio_Series1_NHBE_Mock'] = list(sts.mean(Series1.iloc[:,0:3].iloc[Fila11]) for Fila11 in range (Total_Gen))

In [17]:
Series1

,Series1_NHBE_Mock_1,Series1_NHBE_Mock_2,Series1_NHBE_Mock_3,Series1_NHBE_SARS-CoV-2_1,Series1_NHBE_SARS-CoV-2_2,Series1_NHBE_SARS-CoV-2_3,Promedio_Series1_NHBE_Mock
DDX11L1,0,0,0,0,0,0,0.000000
WASH7P,29,24,23,34,19,44,25.333333
FAM138A,0,0,0,0,0,0,0.000000
FAM138F,0,0,0,0,0,0,0.000000
OR4F5,0,0,0,0,0,0,0.000000
...,...,...,...,...,...,...,...
CDY1B,0,0,0,0,0,0,0.000000
CDY1,0,0,0,0,0,0,0.000000
CSPG4P1Y,0,0,0,0,0,0,0.000000
GOLGA2P3Y,0,0,0,0,0,0,0.000000
GOLGA2P2Y,0,0,0,0,0,0,0.000000